##############################################
# SysGuard Configuration
##############################################

# CPU
CPU_WARNING=70
CPU_CRITICAL=90

# Memory
MEMORY_WARNING=75
MEMORY_CRITICAL=90

# Disk
DISK_WARNING=80
DISK_CRITICAL=95

# Network
PING_HOST="8.8.8.8"
PING_COUNT=2

# Reports
REPORT_DIRECTORY="reports"

# Logs
LOG_DIRECTORY="logs"
LOG_FILE="sysguard.log"

# General
REPORT_TIMESTAMP_FORMAT="%Y-%m-%d_%H-%M-%S"